version: '3.3'
services:

  redis:
    container_name: amon-ra-redis
    image: redis:latest
    restart: always

  postgres:
    container_name: amon-ra-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=amon-ra
      - POSTGRES_USER=amon-ra
      - POSTGRES_PASSWORD=amon-ra

  django:
    container_name: amon-ra-django
    image: mantiby/amon-ra:latest
    restart: always
    ports:
      - 8101:8101
    volumes:
      - /mnt/nostromo/www/amon-ra/static/:/var/lib/amon-ra/static/
      - /mnt/nostromo/www/amon-ra/media/:/var/lib/amon-ra/media/
      - /mnt/nostromo/www/amon-ra/data/:/var/lib/amon-ra/data/
      - /mnt/nostromo/www/amon-ra/log/:/var/log/amon-ra/
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=amon_ra.settings.local
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    command: |
      gunicorn amon_ra.asgi:application --bind 0.0.0.0:8101 --workers 2 --log-file /var/log/amon-ra/wsgi.log

  bot:
    container_name: amon-ra-bot
    image: mantiby/amon-ra:latest
    restart: always
    depends_on:
      - django
    volumes:
      - /home/manti/www/amon-ra/:/srv/amon-ra/src/
      - /mnt/nostromo/www/amon-ra/log/:/var/log/amon-ra/
    environment:
      - DJANGO_HOST=http://django:8101
      - LOG_LEVEL=WARNING
      - LOG_HANDLERS=file
    command: |
      python3 -m amon_ra.bot.main
