version: '3.3'
services:

  helios-django:
    restart: always
    network_mode: host
    image: mantiby/helios:latest
    container_name: helios-django
    ports:
      - 8053:8053
    volumes:
      - /home/manti/www/helios.manti.by/src/:/srv/helios/src/
      - /mnt/nostromo/www/helios/data/:/var/lib/helios/data/
      - /mnt/nostromo/www/helios/static/:/var/lib/helios/static/
      - /mnt/nostromo/www/helios/media/:/var/lib/helios/media/
      - /mnt/nostromo/www/helios/log/:/var/log/helios/
    environment:
      - DJANGO_SETTINGS_MODULE=helios.settings.prod
    command: |
      gunicorn helios.wsgi:application --bind 0.0.0.0:8053 --workers 2 --log-file /var/log/helios/wsgi.log
