version: '3.3'
services:

  redis:
    container_name: helios-redis
    image: redis:latest
    restart: always

  postgres:
    container_name: helios-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=helios
      - POSTGRES_USER=helios
      - POSTGRES_PASSWORD=helios

  django:
    container_name: helios-django
    image: mantiby/helios:latest
    restart: always
    ports:
      - 8101:8101
    volumes:
      - /home/manti/www/helios/:/srv/helios/src/
      - /mnt/nostromo/www/helios/static/:/var/lib/helios/static/
      - /mnt/nostromo/www/helios/media/:/var/lib/helios/media/
      - /mnt/nostromo/www/helios/data/:/var/lib/helios/data/
      - /mnt/nostromo/www/helios/log/:/var/log/helios/
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=helios.settings.prod
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    command: |
      gunicorn helios.wsgi:application --bind 0.0.0.0:8101 --workers 2 --log-file /var/log/helios/wsgi.log
