# Generated by Django 5.0.2 on 2024-03-04 14:09

import amon_ra.apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(default=amon_ra.apps.subscriptions.models.generate_subscription_uuid),
        ),
    ]
