# Generated by Django 5.0.3 on 2024-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_request_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
